
llmops_config:
  pr:
    ENV_NAME: pr
    RUNTIME_NAME: 
    KEYVAULT_NAME:
    SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
    RESOURCE_GROUP_NAME: ${RESOURCE_GROUP_NAME}
    WORKSPACE_NAME: ${WORKSPACE_NAME}
    STANDARD_FLOW_PATH: flows/standard
    EVALUATION_FLOW_PATH: flows/evaluation

  dev:
    ENV_NAME: dev
    RUNTIME_NAME: 
    KEYVAULT_NAME: 
    SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
    RESOURCE_GROUP_NAME: ${RESOURCE_GROUP_NAME}
    WORKSPACE_NAME: ${WORKSPACE_NAME}
    STANDARD_FLOW_PATH: flows/standard
    EVALUATION_FLOW_PATH: flows/evaluation
  
  postprodeval:
    ENV_NAME: postprodeval
    RUNTIME_NAME: 
    KEYVAULT_NAME:
    RESOURCE_GROUP_NAME:
    WORKSPACE_NAME:
    STANDARD_FLOW_PATH: flows/post-production-evaluation
    
datasets_config:
  pr:
    - dataset : temp_dataset
      PROMPT_FLOW_CONFIG_NAME: named_entity_recognition
      ENV_NAME: pr
      DATA_PURPOSE: pr_data
      DATA_PATH: data/data.jsonl
      DATASET_NAME: temp_dataset
      DATASET_DESC: this dataset is for pr validation only

  dev:
    - dataset: named_entity_recognition_test
      PROMPT_FLOW_CONFIG_NAME: named_entity_recognition
      ENV_NAME: dev
      DATA_PURPOSE: test_data
      DATA_PATH: data/eval_data.jsonl
      DATASET_NAME: named_entity_recognition_test
      RELATED_EXP_DATASET: named_entity_recognition_train
      DATASET_DESC: this dataset is for evaluating flows

    - dataset: named_entity_recognition_train
      PROMPT_FLOW_CONFIG_NAME: named_entity_recognition
      ENV_NAME: dev
      DATA_PURPOSE: training_data
      DATA_PATH: data/data.jsonl
      DATASET_NAME: named_entity_recognition_train
      DATASET_DESC: this dataset is for prompt experiments

  postprodeval:  
    - dataset: named_entity_recognition_pp_eval
      PROMPT_FLOW_CONFIG_NAME: named_entity_recognition
      ENV_NAME: postprodeval
      DATA_PURPOSE: post_production_eval_data
      DATA_PATH: data/production_log.jsonl
      DATASET_NAME: named_entity_recognition_pp_eval
      DATASET_DESC: this dataset is for post production evaluation

mapping_config:
  experiment: 
    text: ${data.text}
    entity_type: ${data.entity_type}
  evaluation: 
    evaluation: 
      groundtruth: ${data.results}
      prediction: ${run.outputs.entities}

deployment_configs:
  azure_managed_endpoint:
    dev:
      ENV_NAME: dev
      TEST_FILE_PATH: sample-request.json
      ENDPOINT_NAME: 
      ENDPOINT_DESC: An online endpoint serving a flow for named entity flow
      DEPLOYMENT_DESC: prompt flow deployment
      PRIOR_DEPLOYMENT_NAME: 
      PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION:
      CURRENT_DEPLOYMENT_NAME:
      CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: "100"
      DEPLOYMENT_VM_SIZE: Standard_F4s_v2
      DEPLOYMENT_INSTANCE_COUNT: 1
      ENVIRONMENT_VARIABLES: 
        example-name: example-value
  
  kubernetes_endpoint:
    dev:
      ENV_NAME: dev
      TEST_FILE_PATH: sample-request.json
      ENDPOINT_NAME:
      ENDPOINT_DESC: An kubernetes endpoint serving a flow for named entity
      DEPLOYMENT_DESC: prompt flow deployment
      PRIOR_DEPLOYMENT_NAME:
      PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION:
      CURRENT_DEPLOYMENT_NAME:
      CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: 100,
      COMPUTE_NAME:
      DEPLOYMENT_VM_SIZE:
      DEPLOYMENT_INSTANCE_COUNT: 1
      CPU_ALLOCATION: 
      MEMORY_ALLOCATION: 
      ENVIRONMENT_VARIABLES: 
        example-name: example-value
           
  webapp_endpoint:
    dev:
      ENV_NAME: dev
      TEST_FILE_PATH: sample-request.json
      CONNECTION_NAMES:
        - aoai
      REGISTRY_NAME:
      REGISTRY_RG_NAME:
      APP_PLAN_NAME:
      WEB_APP_NAME:
      WEB_APP_RG_NAME:
      WEB_APP_SKU: "B3"
      USER_MANAGED_ID: