pr: none
trigger:
  branches:
   include:
     - main
     - development
  paths:
    include:
      - .azure-pipelines/*
      - llmops/*
      - web_classification/*

pool:
  vmImage: ubuntu-latest


variables:
- group: llmops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: flow_to_execute
   displayName: "flow to execute"
   default: "web_classification"
 - name: IS_KUBERNETES_DEPLOYMENT
   displayName: "determine managed or kubernetes deployment"
   default: "True"


stages:
  - template: ../../.azure-pipelines/platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      flow_to_execute: ${{ parameters.flow_to_execute }}
      IS_KUBERNETES_DEPLOYMENT: ${{ parameters.IS_KUBERNETES_DEPLOYMENT }}