parameters:
  - name: script_parameter
    type: string

steps:
  - task: AzureCLI@2
    displayName: Execute prompt job
    continueOnError: false
    env: {APPLICATIONINSIGHTS_CONNECTION_STRING: "$(APPLICATIONINSIGHTS-CONNECTION-STRING)"}
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
        ${{parameters.script_parameter}}
