variables:
- name:  PROMPT_FLOW_CONFIG_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.PROMPT_FLOW_CONFIG_NAME'] ]
- name:  KEYVAULT_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.KEYVAULT_NAME'] ]       
- name:  RUNTIME_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.RUNTIME_NAME'] ] 
- name:  AZURE_RM_SVC_CONNECTION
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.AZURE_RM_SVC_CONNECTION'] ] 
- name:  MODEL_BASE_NAME
  value: $[ dependencies.variable_generation.load_config_variables.outputs['loading_model_config.MODEL_BASE_NAME'] ]
- name:  RESOURCE_GROUP_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.RESOURCE_GROUP_NAME'] ]
- name:  WORKSPACE_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.WORKSPACE_NAME'] ]
- name: EXPERIMENT_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.EXPERIMENT_NAME'] ]
- name: MODEL_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.MODEL_NAME'] ]
- name: DEPLOYMENT_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.DEPLOYMENT_NAME'] ]
- name: CONNECTION_NAME
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.CONNECTION_NAME'] ]
- name: STANDARD_FLOW_PATH
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.STANDARD_FLOW_PATH'] ]
- name: EVALUATION_FLOW_PATH
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.EVALUATION_FLOW_PATH'] ]
- name: DATA_CONFIG_PATH
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.DATA_CONFIG_PATH'] ]   
- name: REALTIME_DEPLOYMENT_CONFIG
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.REALTIME_DEPLOYMENT_CONFIG'] ]   
- name: DEPLOY_FLOW_PATH
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.DEPLOY_FLOW_PATH'] ]   
- name: DATA_MAPPING_CONFIG
  value: $[ stageDependencies.variable_generation.load_config_variables.outputs['loading_model_config.DATA_MAPPING_CONFIG'] ]   
  

  