steps:
- task: AzureCLI@2
  name: retrieveAzureServiceConnection
  displayName: Retrieve Azure Service Connection
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      export subscriptionId=$(az account show --query id -o tsv)
      echo "##vso[task.setvariable variable=SUBSCRIPTION_ID]$subscriptionId"
    addSpnToEnvironment: true