parameters:
- name: FLOW_TO_EXECUTE
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: CONNECTION_DETAILS
  type: string
- name: REGISTRY_DETAILS
  type: string
steps:
  parameters:
    step_name: "Create local Connection"
    script_parameter: |
      python -m llmops.common.prompt_local_connections \
        --env_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
        --flow_to_execute ${{ parameters.FLOW_TO_EXECUTE }} \
        --connection_details '${{ parameters.CONNECTION_DETAILS }}'

- task: Bash@3
  displayName: Build Docker Image with flow artifacts
  continueOnError: false
  inputs: 
    targetType: filePath
    filePath: ./llmops/common/scripts/gen_docker_image.sh
  env:
    flow_to_execute: ${{ parameters.flow_to_execute }}
    deploy_environment: ${{ parameters.DEPLOY_ENVIRONMENT }}
    CONNECTION_DETAILS: ${{ parameters.CONNECTION_DETAILS }}
    REGISTRY_DETAILS: ${{ parameters.REGISTRY_DETAILS }}
    build_id: $(Build.BuildNumber)