parameters:
- name: USE_CASE_BASE_PATH
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: CONNECTION_DETAILS
  type: string
- name: REGISTRY_DETAILS
  type: string
steps:
- template: execute_python_code.yml
  parameters:
    step_name: "Create local Connection"
    script_parameter: |
      python -m llmops.common.prompt_local_connections \
        --env_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
        --base_path ${{ parameters.USE_CASE_BASE_PATH }} \
        --connection_details '${{ parameters.CONNECTION_DETAILS }}'

- task: Bash@3
  displayName: Build Docker Image with flow artifacts
  continueOnError: false
  inputs: 
    targetType: filePath
    filePath: ./llmops/common/scripts/gen_docker_image.sh
  env:
    use_case_base_path: ${{ parameters.USE_CASE_BASE_PATH }}
    deploy_environment: ${{ parameters.DEPLOY_ENVIRONMENT }}
    CONNECTION_DETAILS: ${{ parameters.CONNECTION_DETAILS }}
    REGISTRY_DETAILS: ${{ parameters.REGISTRY_DETAILS }}
    build_id: $(Build.BuildNumber)