parameters:
- name: USE_CASE_BASE_PATH
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: CONNECTION_DETAILS
  type: string
- name: REGISTRY_DETAILS
  type: string
steps:
- template: ./prepare_docker_image.yml
  parameters:
    USE_CASE_BASE_PATH: ${{ parameters.USE_CASE_BASE_PATH }}
    DEPLOY_ENVIRONMENT: ${{ parameters.DEPLOY_ENVIRONMENT }}
    CONNECTION_DETAILS: '${{ parameters.CONNECTION_DETAILS }}'
    REGISTRY_DETAILS: '${{ parameters.REGISTRY_DETAILS }}'

- task: AzureCLI@2
  displayName: Webapp deployment
  name: webapp_deployment
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      use_case_base_path=${{ parameters.USE_CASE_BASE_PATH }} deploy_environment=${{ parameters.DEPLOY_ENVIRONMENT }} build_id=$(Build.BuildNumber) CONNECTION_DETAILS='${{ parameters.CONNECTION_DETAILS }}' "./llmops/common/scripts/az_webapp_deploy.sh"