pr: none
trigger:
  branches:
   include:
     - main
     - development
  paths:
    include:
      - .azure-pipelines/*
      - llmops/*
      - math_coding/*


pool:
  vmImage: ubuntu-latest

variables:
- group: llmops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: flow_to_execute
   displayName: "flow to execute"
   default: "math_coding"
 - name: deployment_type
   displayName: "Determine type of deployment - aml, aks, webapp"
   default: "aml"

#=====================================
# Execute platform_ci_dev_pipeline pipeline for experiment, evaluation and deployment of flows
#=====================================
stages:
  - template: ../../.azure-pipelines/platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      flow_to_execute: ${{ parameters.flow_to_execute }}
      deployment_type: ${{ lower(parameters.deployment_type) }}