name: build_validation

on:
  workflow_call:
    inputs:
      flow_type:
        type: string
        description: "The flow use-case to validate"
        required: true
    secrets:
      azure_credentials:
        description: "service principal auth to Azure"
        required: true

jobs:
  validate-code:
    name: job for validating code and structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Load all build validation related dependencies
        shell: bash
        run: |
          set -e # fail on error
          python -m pip install --upgrade pip
          python -m pip install -r .github/requirements/build_validation_requirements.txt
          az version
      - name: Export Secrets 
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: upper
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
      - name: load the current Azure subscription details
        id: subscription_details
        shell: bash
        run: |
          export subscriptionId=$(az account show --query id -o tsv)
          echo "SUBSCRIPTION_ID=$subscriptionId" >> $GITHUB_OUTPUT

      - name: Execute Unit Tests
        shell: bash
        run: |
          pytest ${{ inputs.flow_type }}/tests --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "**/test-*.xml"