name: web_classification_pr_dev_pipeline

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      flow_type:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "web_classification"
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      flow_type:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "web_classification"
  pull_request:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'web_classification/**'


jobs:
  execute-platform-pr-workflow:
    uses: ./.github/workflows/platform_pr_dev_workflow.yml
    with:
      env_name: ${{ inputs.env_name || 'dev'}}
      flow_type: ${{ inputs.flow_type || 'web_classification' }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
