name: web_classification_pr_dev_pipeline

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      use_case_base_path:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "web_classification"
  pull_request:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'web_classification/**'

#=====================================
# Execute platform_pr_dev_workflow workflow for experiment, evaluation and deployment of flows
#=====================================
jobs:
  execute-platform-pr-workflow:
    uses: ./.github/workflows/platform_pr_dev_workflow.yml
    with:
      env_name: ${{ inputs.env_name || 'pr'}}
      use_case_base_path: ${{ inputs.use_case_base_path || 'web_classification' }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
